# Generated by Django 4.1 on 2022-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
