# Generated by Django 4.1 on 2022-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
