# Generated by Django 4.1.1 on 2022-09-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="input_data_location",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="input_script_location",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="output_data_location",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.TextField(),
        ),
    ]
