# Generated by Django 4.1.1 on 2022-09-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FilePathField(verbose_name="/projects/img/"),
        ),
    ]
