# Generated by Django 4.1.1 on 2022-09-29 14:45

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="input_data",
            field=markdownfield.models.MarkdownField(
                null=True, rendered_field="input_data_location"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="input_script",
            field=markdownfield.models.MarkdownField(
                null=True, rendered_field="input_script_location"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="output_data",
            field=markdownfield.models.MarkdownField(
                null=True, rendered_field="output_data_location"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="text",
            field=markdownfield.models.MarkdownField(
                null=True, rendered_field="description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="input_data_location",
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="input_script_location",
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="output_data_location",
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
    ]
