# Generated by Django 4.1.1 on 2022-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_project_input_data_project_input_script_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="input_data",
        ),
        migrations.RemoveField(
            model_name="project",
            name="input_script",
        ),
        migrations.RemoveField(
            model_name="project",
            name="output_data",
        ),
        migrations.RemoveField(
            model_name="project",
            name="text",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="input_data_location",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="input_script_location",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="output_data_location",
            field=models.TextField(null=True),
        ),
    ]
