# Generated by Django 4.1.1 on 2022-10-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_remove_project_input_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroomprojects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("syllabus", models.TextField(null=True)),
                ("instructors", models.TextField(null=True)),
                ("students", models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
